### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './logs/handheld/baby/test/output/000/model.pth

### ISSUE THREAD

**Issue by WillYao-THU** [3d-motion-magnification/3d-motion-mag#4]
Hi, Thanks for your great work!

I wonder if the whole project can be released？

Looking forward to your reply, thanks!

![image](https://github.com/3d-motion-magnification/3d-motion-mag/assets/135940893/100efb29-2df4-4c4a-ac32-54a663375a9f)

**Comment by brandonyfeng** [comment]
What command did you run here? The error seems to be looking for the checkpoint of timestep 000, which would be saved after training with --timestep 000 (see example command in scripts/handheld/run_baby.sh).

**Comment by WillYao-THU** [comment]
> What command did you run here? The error seems to be looking for the checkpoint of timestep 000, which would be saved after training with --timestep 000 (see example command in scripts/handheld/run_baby.sh).

I have solved the problem! Thank you for your response and this excellent job! Could you tell me the approximate training time  for the Blender, Handheld, and Tripod scenes?

**Comment by brandonyfeng** [comment]
In my experience, training the initial scene (timestep = 000) would take about half an hour. The later finetuning would just take a couple of minutes for a single timestep. 
The finetuning could be parallelized (since it only depends on timestep = 000), or executed sequentially (the total time would depend on how many frames / timesteps the scene has).
