### ISSUE TITLE
Implementations for "Linear – Tri-Plane", "Position Shift" and "Encoding Shift" methods

### ISSUE THREAD

**Issue by WillYao-THU** [3d-motion-magnification/3d-motion-mag#5]
Hi, 

I wonder if the release codes include implementations for "Linear – Tri-Plane" ,"Position Shift" and "Encoding Shift" methods. It seems that only the "Phase – Tri-Plane" method is implemented.

Looking forward to your reply, thanks!

**Comment by brandonyfeng** [comment]
We did not plan to include them because we wanted to repo to only contain the functionality used by the method.

"Linear - Tri-Plane" is straightforward to implement. Here, we don't need the steerable pyramid, and we just compute: T1_mag = T1 + alpha * (T1 - T0) directly on the triplane values.

"Position Shift" and "Encoding Shift" depend on a non-triplane NeRF backbone (including them would make this repo too complicated). 
Basically, it would require training the NeRF using the original MLP setup: (x, y, z) -> PosEnc(x, y, z) -> MLP(PosEnc(x, y, z)) -> (RGB, opacity).
With "Position Shift", we would only tweak (x, y, z) and freeze everything else for later timesteps.
With "Encoding Shift", we would only finetune the Positional Encoding output.
The finetuning essentially learns a residual term to add back to the original value.
After all training, magnification is obtained by linearly amplifying the differences characterized by the residuals.

Let me know if you need further clarifications. Thanks.

**Comment by WillYao-THU** [comment]
Thank you so much for your detailed explanation. Your clarification on the implementation was incredibly helpful. Best regards!

**Comment by gmcribeiro** [comment]
Hello!

I have a few questions about the Position Shift and Encoding Shift methods.

1. Do you train a separate MLP for each timestep using only *(x, y, z)* as input, or do you train a single MLP that receives 
*((x, y, z), t)* (where t denotes the timestep)?

2. In the magnification stage, what mechanism do you use to amplify the motion?

   * Do you apply a scalar factor α to the predicted offsets, such as:
	   * (x, y, z) -> Position Shift MLP ->(Δx, Δy, Δz) -> (x, y, z) + α(Δx, Δy, Δz) -> Encoder -> NeRF
	   * P -> Encoding Shift MLP -> (Φ<sub>1</sub>, (...), Φ<sub>k</sub>) -> α(Φ<sub>1</sub>, (...), Φ<sub>k</sub>) -> Encoder \[sin(P+αΦ<sub>1</sub>), cos(P+αΦ<sub>2</sub>), (...), sin(2<sup>i</sup>P+αΦ<sub>k-1</sub>), cos(2<sup>i</sup>P+αΦ<sub>k</sub>)] -> NeRF

   * Or, do you use an FFT-based method for magnification? If so, could you outline how the FFT is incorporated into the pipeline, or point to a resource that explains the approach?

Thank you in advance for the clarification.

**Comment by brandonyfeng** [comment]
@gmcribeiro 
1. Should be the latter case with t in the input
2. Should just be scaling the predicted offset. FFT is for filtering, which was introduced in the earlier papers on motion magnification (Eulerian and Phase-based) where you could find the explanations.

**Comment by gmcribeiro** [comment]
Thank you for the clarification! Best regards!
